[package]
name = "uno-r4-rust"
version = "0.1.0"
edition = "2024"

[dependencies]
cortex-m = { version = "0.7.7" }
cortex-m-rt = "0.7.5"
panic-halt = "1.0.0"

[[bin]]
name = "uno-r4-rust"
test = false
bench = false
